# Agent Registry Configuration
# Copy this file to your project root and customize as needed

# Central registry repository
registry:
  repo: gahyun-git/mimic-skills

# Version pinning
# Options:
#   - Specific version: "1.2.0"
#   - Latest: "latest" (not recommended for production)
version: "1.0.0"

# Auto-update settings
auto_update:
  # Enable weekly update check PRs
  enabled: true

  # Schedule (cron format) - default: every Monday at 9am UTC
  schedule: "0 9 * * 1"

  # PR settings
  pr:
    # Auto-merge is disabled by design (manual review required)
    auto_merge: false

    # PR labels
    labels:
      - "dependencies"
      - "agent-registry"

    # Reviewers (optional)
    # reviewers:
    #   - "username1"
    #   - "username2"

# Sync settings
sync:
  # Target directory for .agent/ files
  target_dir: "."

  # Backup existing .agent/ before sync
  backup_existing: true

  # Files/directories to preserve during sync (glob patterns)
  # These won't be overwritten from the registry
  preserve:
    - ".agent/config/user-preferences.yaml"
    - ".agent/config/local-*"
