# Consumer Workflow: Check for Agent Registry Updates
# Copy this file to your project: .github/workflows/check-registry-updates.yml
#
# This workflow checks for new versions of the agent registry and creates
# a PR if updates are available. Auto-merge is intentionally disabled.

name: Check Agent Registry Updates

on:
  schedule:
    # Run weekly on Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read current version
        id: current
        run: |
          if [ -f ".agent-registry.yaml" ]; then
            VERSION=$(grep -E '^version:' .agent-registry.yaml | sed 's/version:[[:space:]]*"\?\([^"]*\)"\?/\1/')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version=0.0.0" >> $GITHUB_OUTPUT
          fi
          echo "Current version: $VERSION"

      - name: Get latest registry version
        id: latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO: Replace with your registry repo
          REGISTRY_REPO: gahyun-git/mimic-skills
        run: |
          LATEST=$(gh api "repos/${REGISTRY_REPO}/releases/latest" --jq '.tag_name' | sed 's/^v//')
          echo "version=$LATEST" >> $GITHUB_OUTPUT
          echo "Latest version: $LATEST"

      - name: Compare versions
        id: compare
        env:
          CURRENT_VERSION: ${{ steps.current.outputs.version }}
          LATEST_VERSION: ${{ steps.latest.outputs.version }}
        run: |
          if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
            echo "Already up to date"
            echo "needs_update=false" >> $GITHUB_OUTPUT
          else
            echo "Update available: $CURRENT_VERSION -> $LATEST_VERSION"
            echo "needs_update=true" >> $GITHUB_OUTPUT
          fi

      - name: Create update PR
        if: steps.compare.outputs.needs_update == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_VERSION: ${{ steps.current.outputs.version }}
          LATEST_VERSION: ${{ steps.latest.outputs.version }}
        run: |
          BRANCH_NAME="agent-registry-update-${LATEST_VERSION}"

          # Check if PR already exists
          EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')
          if [ -n "$EXISTING_PR" ]; then
            echo "PR already exists: #$EXISTING_PR"
            exit 0
          fi

          # Create branch and update version
          git checkout -b "$BRANCH_NAME"

          # Update .agent-registry.yaml
          sed -i "s/^version:.*/version: \"${LATEST_VERSION}\"/" .agent-registry.yaml

          # Commit and push
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .agent-registry.yaml
          git commit -m "chore(deps): update agent-registry to ${LATEST_VERSION}"
          git push origin "$BRANCH_NAME"

          # Create PR
          gh pr create \
            --title "chore(deps): update agent-registry to ${LATEST_VERSION}" \
            --body "$(cat <<EOF
          ## Agent Registry Update Available

          **Current version:** ${CURRENT_VERSION}
          **New version:** ${LATEST_VERSION}

          ### What's included
          - Updated agent skills and workflows from central registry
          - See [CHANGELOG](https://github.com/gahyun-git/mimic-skills/blob/main/CHANGELOG.md) for details

          ### Before merging
          1. Review the changes in the registry CHANGELOG
          2. Run \`sync-agent-registry\` workflow after merging to apply changes

          ---
          *This PR was automatically created by the registry update checker.*
          *Auto-merge is disabled by design - manual review required.*
          EOF
          )" \
            --label "dependencies" \
            --label "agent-registry"

          echo "Created PR for version $LATEST_VERSION"
